name: MobTime Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14.0.2
          java-package: jdk+fx
      - name: Build with Gradle
        run: ./gradlew jpackage -PinstallerType=deb
      - run: ls build/jpackage
      - uses: actions/upload-artifact@v2
        with:
          name: MobTime
          path: build/jpackage/mobtime_[0-9\.]+-1_amd64.deb
