name: MobTime Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: joschi/setup-jdk@v2
        with:
          java-version: '14' # The OpenJDK version to make available on the path
      - name: Download JFX JMods
        shell: powershell
        run: Invoke-WebRequest -Uri https://gluonhq.com/download/javafx-14-0-1-jmods-windows/ -OutFile openjfx-14.0.1_windows-x64_bin-jmods.zip
      - name: Unzip JFX
        shell: powershell
        run: Expand-Archive -Path openjfx-14.0.1_windows-x64_bin-jmods.zip -Force
      - name: List directory
        shell: powershell
        run: ls openjfx-14.0.1_windows-x64_bin-jmods
      - name: Download Wix
        shell: powershell
        run: Invoke-WebRequest -Uri https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311.exe -OutFile wix311.exe
      - name: Install Wix
        shell: powershell
        run: wix311.exe /install /quiet /norestart
      - name: List directory
        shell: powershell
        run: ls -al
