name: MobTime Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: sormuras/download-jdk@v1
        id: jdk
          with:
            feature: 14
      - uses: actions/setup-java@v1
          with:
            java-version: ${{ steps.jdk.outputs.version }}
            jdkFile: ${{ steps.jdk.outputs.file }}
            java-package: jdk+fx
      - name: Build with Gradle
        run: ./gradlew.bat jpackage -PinstallerType=msi